# Generated by Django 5.0.6 on 2024-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('apellido', models.CharField(default='Apellido', max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('ciudad', models.CharField(default='Ciudad', max_length=100)),
                ('puesto', models.CharField(default='Puesto', max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_contratacion', models.DateField(default='2000-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Direccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
